# https://openssl-library.org/source/
# The current releases are signed by the OpenSSL key with fingerprint BA54 73A2 B058 7B07 FB27 CF2D 2160 94DF D0CB 81EF.

FROM docker.io/library/alpine:3.21.3 AS build
RUN apk update
RUN apk add make perl gcc musl-dev linux-headers gnupg gpg
ARG OPENSSL_VERSION=3.0.16
WORKDIR /openssl/
#RUN wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
#RUN wget https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz -O openssl.tar.gz
RUN wget https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz
RUN wget https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz.asc
RUN wget https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz.sha1
RUN wget https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz.sha256
RUN wget https://keys.openpgp.org/vks/v1/by-fingerprint/BA5473A2B0587B07FB27CF2D216094DFD0CB81EF -O BA5473A2B0587B07FB27CF2D216094DFD0CB81EF.asc
RUN sha1sum -c openssl-3.0.16.tar.gz.sha1
RUN sha256sum -c openssl-3.0.16.tar.gz.sha256
RUN gpg --keyserver 'keys.openpgp.org' --recv-keys 'BA5473A2B0587B07FB27CF2D216094DFD0CB81EF'
RUN gpg --verify openssl-3.0.16.tar.gz.asc openssl-3.0.16.tar.gz
#RUN tar -x -f openssl-${OPENSSL_VERSION}.tar.gz -C . --strip-components 1
#RUN rm openssl-${OPENSSL_VERSION}.tar.gz
#WORKDIR /openssl/openssl-${OPENSSL_VERSION}/
RUN tar -x -f openssl-3.0.16.tar.gz -C . --strip-components 1
RUN ./config --static -static
RUN make
RUN make test
RUN make install

FROM scratch
COPY --from=build /usr/local/bin/openssl /openssl
USER 1324:1324
ENTRYPOINT ["/openssl"]
CMD ["version"]