# https://openssl-library.org/source/
# The current releases are signed by the OpenSSL key with fingerprint BA54 73A2 B058 7B07 FB27 CF2D 2160 94DF D0CB 81EF.
# https://wiki.openssl.org/index.php/Compilation_and_Installation

FROM docker.io/library/alpine:3.21.3 AS build
RUN apk update
RUN apk add make perl gcc musl-dev linux-headers gnupg gpg
ARG VERSION=3.0.16
WORKDIR /openssl/
RUN wget https://github.com/openssl/openssl/releases/download/openssl-${VERSION}/openssl-${VERSION}.tar.gz
# verify
RUN wget https://github.com/openssl/openssl/releases/download/openssl-${VERSION}/openssl-${VERSION}.tar.gz.asc
RUN wget https://github.com/openssl/openssl/releases/download/openssl-${VERSION}/openssl-${VERSION}.tar.gz.sha1
RUN wget https://github.com/openssl/openssl/releases/download/openssl-${VERSION}/openssl-${VERSION}.tar.gz.sha256
#RUN wget https://keys.openpgp.org/vks/v1/by-fingerprint/BA5473A2B0587B07FB27CF2D216094DFD0CB81EF -O BA5473A2B0587B07FB27CF2D216094DFD0CB81EF.asc
RUN sha1sum -c openssl-${VERSION}.tar.gz.sha1
RUN sha256sum -c openssl-${VERSION}.tar.gz.sha256
#ARG KEY=BA5473A2B0587B07FB27CF2D216094DFD0CB81EF
RUN gpg --keyserver 'keys.openpgp.org' --recv-keys 'BA5473A2B0587B07FB27CF2D216094DFD0CB81EF'
RUN gpg --verify openssl-${VERSION}.tar.gz.asc openssl-${VERSION}.tar.gz
RUN tar -x -f openssl-${VERSION}.tar.gz -C . --strip-components 1
RUN ./config --static -static
RUN make
RUN make test
RUN make install

FROM scratch
COPY --from=build /usr/local/bin/openssl /openssl
USER 1324:1324
ENTRYPOINT ["/openssl"]
CMD ["version"]