apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment
  labels:
    app: lala
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling
  template:
    metadata:
      labels:
        app: rolling
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: rolling
        image: rolling:1
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 0
       maxSurge: 1