apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment
  labels:
    app: rolling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: rolling
        image: rolling:1
        ports:
        - containerPort: 8080
