services:
  rmq:
    image: 'docker.io/library/rabbitmq:4.1.0-alpine'
    tmpfs:
      - /var/lib/rabbitmq
  perf:
    image: rabbitmq-pref:17-2.23.0
    build:
      context: .
      dockerfile_inline: |
        FROM docker.io/library/sapmachine:17.0.15-jre-alpine
        RUN cd / && wget https://github.com/rabbitmq/rabbitmq-perf-test/releases/download/v2.23.0/perf-test-2.23.0.jar
    entrypoint: java
    command: ["-jar", "perf-test-2.23.0.jar", "--time", "16", "--uri", "amqp://guest:guest@rmq:5672"]
    depends_on:
      rmq:
        condition: service_started